"""
366 "On this day in words" facts — one per calendar day (including Feb 29).
Keys are "MM-DD" strings. Each value is a single punchy sentence about word
origins, language history, literary milestones, or communication breakthroughs.
"""

WORD_HISTORY: dict[str, str] = {
    # ── January ──────────────────────────────────────────────────────────────
    "01-01": "The word 'January' comes from Janus, the two-faced Roman god of beginnings — the only deity who could look both forward and back.",
    "01-02": "'Serendipity' was coined in 1754 by Horace Walpole, inspired by a Persian fairy tale about three lucky princes of 'Serendip.'",
    "01-03": "J.R.R. Tolkien was born today in 1892 — he invented entire languages for Middle-earth, including Quenya and Sindarin.",
    "01-04": "'Saxophone' is named after its inventor Adolphe Sax — one of the very few instruments in history named after the person who made it.",
    "01-05": "'Paradise' entered English from Persian *pairi-daēza* meaning 'walled garden' — originally a word for a royal Persian enclosure.",
    "01-06": "Samuel Morse publicly demonstrated his telegraph today in 1838, forever changing how written words travel across distances.",
    "01-07": "'Galaxy' comes from the Greek *galakt-* meaning milk — because the ancients thought the Milky Way was Hera's spilled breast milk.",
    "01-08": "'Auld Lang Syne' is Scots for 'old long since,' meaning times gone by — Robert Burns wrote it down around 1788.",
    "01-09": "'Manuscript' literally means 'written by hand' — from Latin *manus* (hand) + *scriptus* (written).",
    "01-10": "'Disaster' derives from Italian *disastro*, 'bad star' — when astrology ruled, unfavorable stars meant catastrophe.",
    "01-11": "'Insulin' was first used on a human patient today in 1922 — the name comes from Latin *insula* (island), for the islets of Langerhans.",
    "01-12": "The word 'algorithm' is named after 9th-century Persian mathematician al-Khwarizmi, whose name Latinised to 'Algorismus.'",
    "01-13": "The word 'jazz' first appeared in print in a San Francisco newspaper today in 1913 — its ultimate origin remains hotly debated.",
    "01-14": "'Hazard' reached English via French from Arabic *az-zahr*, meaning 'the dice' — a game of chance.",
    "01-15": "Wikipedia launched today in 2001 — 'wiki' comes from Hawaiian *wiki-wiki*, meaning 'quick.'",
    "01-16": "In 1936 'pneumonoultramicroscopicsilicovolcanoconiosis' was entered into a dictionary, creating English's longest recognized word.",
    "01-17": "Benjamin Franklin, born today in 1706, coined scientific terms like 'electricity,' 'conductor,' 'battery,' and 'positive' charge.",
    "01-18": "'Robot' debuted in Karel Čapek's 1920 play R.U.R., from Czech *robota* meaning 'drudgery' or 'forced labor.'",
    "01-19": "Edgar Allan Poe was born today in 1809 — he invented detective fiction and is credited with popularising the term 'short story.'",
    "01-20": "'Inauguration' comes from Latin *inaugurare* — Romans observed birds' flight to read omens before any important ceremony.",
    "01-21": "'Vaccine' comes from Latin *vacca* (cow), because Edward Jenner used cowpox to vaccinate against smallpox in 1796.",
    "01-22": "'Decision' comes from Latin *decidere*, to cut away — making a choice was literally about cutting off all other options.",
    "01-23": "'Hazard' and 'chess' share a common Semitic origin — both games traveled to Europe via the Arab world in the Middle Ages.",
    "01-24": "The California Gold Rush started today in 1848; 'bonanza' — Spanish for 'good weather' at sea — entered English as a word for a windfall.",
    "01-25": "Robert Burns Night is celebrated today — 'auld' in 'Auld Lang Syne' is Scots for 'old,' from Old English *eald*.",
    "01-26": "'Kangaroo' is believed to come from *gangurru*, a word in the Guugu Yimithirr Aboriginal language of Queensland.",
    "01-27": "Mozart was born today in 1756 — 'sonata' comes from Italian *sonare* (to sound), contrasted with 'cantata' (*cantare*, to sing).",
    "01-28": "'The Raven' by Poe was published today in 1845, giving the word 'nevermore' its place in literary immortality.",
    "01-29": "'Spaghetti' is Italian for 'little strings,' from *spago* (string) — the word first entered English around 1888.",
    "01-30": "'Mahatma' — as in Gandhi — is Sanskrit for 'great soul': *maha* (great) + *atma* (soul).",
    "01-31": "The 13th Amendment abolishing slavery passed Congress today in 1865 — 'emancipate' comes from Latin *emancipare*, to free.",

    # ── February ─────────────────────────────────────────────────────────────
    "02-01": "'February' comes from Latin *februum*, a purification ritual the Romans held on the 15th of this month.",
    "02-02": "'Groundhog' is a North American coinage from 1784; the same animal is called 'woodchuck,' from the Algonquian word *otchock*.",
    "02-03": "Buddy Holly died today in 1959 — 'music' traces to Greek *mousike*, the art of the Muses, divine daughters of memory.",
    "02-04": "Facebook launched today in 2004 — 'social' traces to Latin *socius*, meaning companion or ally.",
    "02-05": "'Mile' comes from Latin *mille passuum*, one thousand paces — the Roman legions literally paced out their roads.",
    "02-06": "Murray Gell-Mann, born today in 1929, named the 'quark' after a nonsense word in James Joyce's *Finnegans Wake*.",
    "02-07": "Charles Dickens was born today in 1812 — he coined 'butterfingers,' 'cheesiness,' 'flummox,' and 'boredom.'",
    "02-08": "The first radio was installed in the White House today in 1922 — 'radio' is short for *radiotelegraphy*, from Latin *radius* (ray).",
    "02-09": "'Carnival' comes from Latin *carne vale*, meaning 'farewell to meat' — the feast before Lent begins.",
    "02-10": "'Treaty' comes from Latin *tractatus*, a drawing-out or discussion — diplomacy is literally about stretching words.",
    "02-11": "Thomas Edison, born today in 1847, proposed 'hello' as the standard telephone greeting — his rival Bell preferred 'ahoy.'",
    "02-12": "Charles Darwin was born today in 1809 — 'evolution' comes from Latin *evolutio*, an unrolling, like a scroll being opened.",
    "02-13": "'Valentine' as a word for a sweetheart entered English around 1440 — before that it was only a saint's name.",
    "02-14": "'Chocolate' comes from Nahuatl *xocolatl* — Spanish conquistadors first encountered it in Aztec courts in the early 1500s.",
    "02-15": "Galileo was born today in 1564 — 'telescope' is from Greek *tele* (far) + *skopein* (to look).",
    "02-16": "'Amber' entered English from Arabic *anbar*, which originally referred to ambergris, a precious perfume ingredient.",
    "02-17": "'Heresy' comes from Greek *hairesis*, a choice or taking — choosing a different belief was literally an act of selection.",
    "02-18": "Toni Morrison, born today in 1931, became the first African American woman to win the Nobel Prize in Literature in 1993.",
    "02-19": "Copernicus was born today in 1473 — his ideas sparked a 'Copernican revolution,' a phrase now meaning any total paradigm shift.",
    "02-20": "'Pioneer' comes from Old French *paonier*, a foot soldier who went ahead of the army to clear the road.",
    "02-21": "The Communist Manifesto was published today in 1848 — 'manifesto' is Italian for 'public declaration,' from Latin *manifestus*.",
    "02-22": "George Washington was born today in 1732 — 'president' comes from Latin *praesidens*, one who sits before and presides.",
    "02-23": "Gutenberg's Bible was printed today in 1455 — the first major book printed with movable type, launching the age of mass literacy.",
    "02-24": "'Athlete' comes from Greek *athlos*, a contest or prize — the first Olympic champions were immortalised in verse.",
    "02-25": "'Mardi Gras' is French for 'Fat Tuesday,' referring to the last indulgent eating before the Lenten fast.",
    "02-26": "Victor Hugo was born today in 1802 — his *Les Misérables* contains a sentence that runs to 823 words in the original French.",
    "02-27": "Henry Wadsworth Longfellow was born today in 1807, whose 'Paul Revere's Ride' gave history a legendary — if slightly inaccurate — retelling.",
    "02-28": "'Leap year' is named so because fixed calendar dates 'leap' forward by an extra weekday compared to ordinary years.",
    "02-29": "Leap Day — 'intercalary' (the term for this inserted day) comes from Latin *intercalare*, to place between — rare as a Feb 29 birthday.",

    # ── March ────────────────────────────────────────────────────────────────
    "03-01": "'March' is named after Mars, the Roman god of war — the month originally opened the military campaigning season.",
    "03-02": "Dr. Seuss was born today in 1904 — his books are celebrated for 'nonce words,' invented purely for sound and rhythm.",
    "03-03": "Alexander Graham Bell was granted his telephone patent today in 1876 — the word 'hello' only became a greeting because of it.",
    "03-04": "'Pennsylvania' is Latin-Welsh for 'Penn's Woods' — from William Penn + Latin *sylvanus* (of the forest).",
    "03-05": "'Slogan' comes from Scottish Gaelic *sluagh-ghairm*, the battle cry of a clan, once howled across hillsides.",
    "03-06": "Michelangelo was born today in 1475 — 'renaissance' means 'rebirth' in both French and Italian.",
    "03-07": "Alexander Graham Bell made the first intelligible telephone call today in 1876 — 'Mr. Watson, come here, I want to see you.'",
    "03-08": "'Feminist' (from French *féministe*) first appeared in print in 1895 — International Women's Day is marked today.",
    "03-09": "'Platform' comes from French *plate-forme* (flat form) — by 1640 it had evolved to mean a political programme.",
    "03-10": "'Quarantine' comes from Italian *quarantina giorni* — forty days — the isolation period Venetian ships observed during the Black Death.",
    "03-11": "'Pandemic' comes from Greek *pan* (all) + *demos* (people) — a disease literally 'of all the people.'",
    "03-12": "'Scout' comes from Old French *escouter*, to listen or spy — the word carried a sense of stealthy observation.",
    "03-13": "'Dinosaur' was coined in 1842 from Greek *deinos* (terrible) + *sauros* (lizard) by anatomist Richard Owen.",
    "03-14": "Pi Day — 'pi' (π) was first used for the circle ratio by Welsh mathematician William Jones in 1706.",
    "03-15": "The Ides of March — 'ides' from Latin *idus*, marking the middle of the Roman month; Caesar was warned, and ignored it.",
    "03-16": "'Rocket' comes from Italian *rochetta*, a small spindle — Robert Goddard launched the first liquid-fuelled rocket today in 1926.",
    "03-17": "'Leprechaun' comes from Old Irish *luchorpán*, meaning 'small body' — and 'shamrock' from Irish *seamróg*, a clover.",
    "03-18": "'Astronaut' from Greek *astron* (star) + *nautes* (sailor) — Alexei Leonov performed the first spacewalk today in 1965.",
    "03-19": "'March' as a verb (to march) comes from Old French *marchier*, to trample — the month's name is entirely unrelated.",
    "03-20": "'Equinox' from Latin *aequus* (equal) + *nox* (night) — the one day a year when night and day are perfectly balanced.",
    "03-21": "Johann Sebastian Bach was born today in 1685 — 'baroque' comes from Portuguese *barroco*, an irregular or imperfect pearl.",
    "03-22": "'Wilderness' comes from Old English *wildēornes*, literally 'the place of wild deer.'",
    "03-23": "Patrick Henry reportedly said 'Give me liberty, or give me death!' today in 1775 — 'liberty' from Latin *libertas*.",
    "03-24": "Harry Houdini was born today in 1874 — 'abracadabra' may come from Aramaic *avra kadabra*, 'I will create as I speak.'",
    "03-25": "'Lady Day,' once the medieval New Year in England — the word 'lady' comes from Old English *hlæfdige*, loaf-kneader.",
    "03-26": "Tennessee Williams was born today in 1911 — 'catastrophe' comes from Greek *katastrophē*, an overturning or sudden ending.",
    "03-27": "'Theatre' comes from Greek *theatron*, a place for viewing — from *theaomai*, to behold.",
    "03-28": "'Nuclear' comes from Latin *nucleus*, a kernel or nut — the atom is named after Greek *atomos*, something indivisible.",
    "03-29": "Alaska was sold to the US today in 1867 — 'Alaska' comes from the Aleut *alaxsxaq*, meaning 'great land.'",
    "03-30": "'Utopia' was coined by Thomas More in 1516 from Greek *ou* (not) + *topos* (place) — meaning 'nowhere.'",
    "03-31": "'Bunny' may derive from 'bun,' a 16th-century word for a rabbit of unknown origin — first recorded in Middle English.",

    # ── April ────────────────────────────────────────────────────────────────
    "04-01": "'Fool' comes from Old French *fol*, mad, related to Latin *follis* — a bellows, something puffed up with air and empty.",
    "04-02": "Hans Christian Andersen was born today in 1805 — 'fairy tale' as a genre label comes from French *conte de fée*.",
    "04-03": "'Outlaw' comes from Old English *utlaga*, one placed outside the law — a term borrowed directly from Viking legal codes.",
    "04-04": "'President' comes from Latin *praesidens*, one who sits before — William Henry Harrison's presidency lasted only 32 days.",
    "04-05": "Booker T. Washington was born today in 1856 — the word 'Tuskegee' derives from the Muscogee Creek language.",
    "04-06": "Peter Mark Roget published his famous thesaurus today in 1852 — 'thesaurus' means 'treasury' in both Greek and Latin.",
    "04-07": "'Health' comes from Old English *hælth*, wholeness — it shares the same root as 'holy,' 'heal,' and even 'hello.'",
    "04-08": "'Avant-garde' is French for 'advance guard' — the military scouts who go first, before anyone else.",
    "04-09": "'Alphabet' is named from the first two Greek letters: *alpha* (from Phoenician *aleph*, an ox) + *beta* (*beth*, a house).",
    "04-10": "'Titanic' comes from the Titans of Greek mythology — beings of enormous size, strength, and, ultimately, defeat.",
    "04-11": "'April' may derive from Latin *aperire* (to open), for flowers opening — or possibly from Aphrodite, goddess of love.",
    "04-12": "Yuri Gagarin became the first human in space today in 1961 — 'cosmonaut' from Greek *kosmos* (universe) + *nautes* (sailor).",
    "04-13": "Thomas Jefferson was born today in 1743 — he popularised words like 'pedicure,' 'belittle,' and 'indecipherable.'",
    "04-14": "'Assassinate' comes from Arabic *hashshashin*, a sect of medieval killers — Lincoln was shot on this night in 1865.",
    "04-15": "'Tax' comes from Latin *taxare* (to touch or handle, to estimate) — the earliest tax records come from Sumer, around 2500 BCE.",
    "04-16": "'Slapstick' comedy was named after a hinged paddle used in commedia dell'arte that made a slapping sound when actors were 'hit.'",
    "04-17": "'Syntax' comes from Greek *syntaxis*, arrangement — the discipline of putting words in order to create meaning.",
    "04-18": "'Tremor' comes from Latin *tremere*, to tremble — San Francisco shook catastrophically today in 1906.",
    "04-19": "'Patriot' comes from Greek *patriōtēs*, fellow countryman — the first shots of the American Revolution were fired today in 1775.",
    "04-20": "'Canvas' and 'cannabis' are the same word — hemp was woven into canvas for centuries before the plant became notorious.",
    "04-21": "Charlotte Brontë was born today in 1816 — she and her sisters published under male pen names to be taken seriously as writers.",
    "04-22": "'Ecology' from Greek *oikos* (house) + *logos* (study) — the science of our planetary home, first named on Earth Day 1970.",
    "04-23": "Shakespeare was born (and died) on April 23 — he invented over 1,700 English words, including 'bedroom,' 'lonely,' and 'obscene.'",
    "04-24": "'Genocide' was coined in 1944 from Greek *genos* (race) + Latin *caedere* (to kill) — a new word for an ancient horror.",
    "04-25": "Watson and Crick published the structure of DNA today in 1953 — 'DNA' stands for deoxyribonucleic acid.",
    "04-26": "Shakespeare was baptised today in 1564 — the man who arguably shaped more English vocabulary than any other single writer.",
    "04-27": "Samuel Morse was born today in 1791 — his code compressed language into dots and dashes, making distance irrelevant.",
    "04-28": "'Thrill' originally meant to pierce — from Old English *thyrlian* (to perforate), the same root as 'nostril.'",
    "04-29": "'Duke' comes from Latin *dux*, leader or general — Roman commanders who led armies.",
    "04-30": "'Witch' comes from Old English *wicca*, a wise person — the word was gender-neutral before it became exclusively pejorative.",

    # ── May ──────────────────────────────────────────────────────────────────
    "05-01": "'Mayday' (distress call) comes from French *m'aider* (help me) — completely unrelated to the month of May.",
    "05-02": "'Propaganda' comes from Latin *propagare* (to spread plants by layering) — the Church used it for spreading the faith in 1622.",
    "05-03": "'Hero' comes from Greek *hēros*, originally meaning a demigod — someone between mortal and divine.",
    "05-04": "Star Wars Day — 'Force' comes from Latin *fortia*, strength; 'May the Fourth be with you' is the purest accidental pun.",
    "05-05": "'Cinco' is Spanish for five, from Latin *quinque* — itself from Proto-Indo-European *penkwe*, the ancestor of English 'five.'",
    "05-06": "Sigmund Freud was born today in 1856 — he gave English 'ego,' 'id,' 'libido,' and 'psychoanalysis.'",
    "05-07": "'Concerto' comes from Italian *concertare*, to harmonise — to bring competing elements into a unified whole.",
    "05-08": "'Victory' comes from Latin *victoria*, from *vincere* (to conquer) — VE Day, 1945.",
    "05-09": "'Mnemonic' comes from Greek *mnemonikos* (of memory), after Mnemosyne, the goddess of memory and mother of the Muses.",
    "05-10": "The transcontinental railroad was completed today in 1869 — 'locomotive' from Latin *locus* (place) + *motivus* (of motion).",
    "05-11": "'Piano' is short for 'pianoforte' — Italian for 'soft-loud,' because the instrument could play at different volumes.",
    "05-12": "Florence Nightingale was born today in 1820 — 'nurse' comes from Old French *norrice*, one who nourishes.",
    "05-13": "'Humane' and 'human' are the same Latin word *humanus* — treating people well was once the very definition of being human.",
    "05-14": "'Israel' (declared today in 1948) is from Hebrew meaning 'one who struggles with God' — *sara* (to strive) + *El* (God).",
    "05-15": "'Nylon' was not an acronym — DuPont invented it as a meaningless but distinctive brand sound.",
    "05-16": "'Maverick' entered the language from Samuel Augustus Maverick, a Texas rancher who famously refused to brand his cattle.",
    "05-17": "'Constitution' comes from Latin *constituere*, to establish firmly — the foundation that holds everything else in place.",
    "05-18": "'Malaria' comes from Italian *mala aria*, bad air — before germ theory, miasmas (bad smells) were blamed for disease.",
    "05-19": "'Volcano' comes from *Vulcanus*, the Roman god of fire — Mount St. Helens erupted catastrophically today in 1980.",
    "05-20": "Charles Lindbergh took off for Paris today in 1927 — 'aviator' comes from Latin *avis* (bird).",
    "05-21": "'Explore' comes from Latin *explorare*, to search out — Magellan's crew completed the first circumnavigation today in 1521.",
    "05-22": "Arthur Conan Doyle was born today in 1859 — Holmes's famous deduction is technically *abductive* reasoning, not deductive.",
    "05-23": "'Trophy' comes from Greek *tropaion*, a monument built where an enemy turned to flee — from *tropē*, a turning.",
    "05-24": "The first official telegraph message was sent today in 1844: 'What hath God wrought?' — a quote from Numbers 23:23.",
    "05-25": "'Towel' first appeared in English around 1300 — Douglas Adams made this date 'Towel Day,' honouring *The Hitchhiker's Guide*.",
    "05-26": "'Impeach' comes from Old French *empechier*, to hinder — literally to put a foot in the path of power.",
    "05-27": "Rachel Carson was born today in 1907 — she popularised 'ecology' and introduced 'biocide' to describe pesticide damage.",
    "05-28": "Ian Fleming was born today in 1908 — he borrowed 'James Bond' from an ornithologist whose field guide he kept at his desk.",
    "05-29": "Edmund Hillary and Tenzing Norgay summited Everest today in 1953 — 'summit' from Old French *somet*, top of a hill.",
    "05-30": "'Memorial' comes from Latin *memorialis*, belonging to memory — the root of 'memoir,' 'memorise,' and 'remember.'",
    "05-31": "'Clue' originally meant a ball of yarn (*clew*), used by Theseus to navigate the labyrinth — it evolved to mean any guiding hint.",

    # ── June ─────────────────────────────────────────────────────────────────
    "06-01": "'June' is named after Juno, Roman goddess of marriage — historically the most popular month for weddings.",
    "06-02": "'Coronation' comes from Latin *corona* (crown) — Queen Elizabeth II was crowned today in 1953.",
    "06-03": "'Tank' (military) was a deliberate code name used by British engineers in WWI to disguise their new weapon as water carriers.",
    "06-04": "'Environment' comes from Old French *environner*, to surround — World Environment Day is June 5.",
    "06-05": "'Ecology' was coined in 1866 from Greek *oikos* (house) — World Environment Day celebrates our planetary house.",
    "06-06": "D-Day, 1944 — 'D-Day' is a military term where 'D' simply stands for 'day,' just as 'H-Hour' uses H for hour.",
    "06-07": "Alan Turing was born today in 1912 — he called his machine-intelligence test the 'Imitation Game,' not the Turing Test.",
    "06-08": "'Utopia' was coined by Sir Thomas More in 1516 from Greek *ou* (not) + *topos* (place) — a word for 'no-place.'",
    "06-09": "'Anagram' comes from Greek *ana* (back) + *gramma* (letter) — 'listen' is an anagram of 'silent.'",
    "06-10": "'Anonymous' comes from Greek *an-* (without) + *onoma* (name) — Alcoholics Anonymous was founded today in 1935.",
    "06-11": "'Jungle' comes from Hindi/Marathi *jangal*, a wasteland or scrubland — the word originally meant dry and barren, not lush.",
    "06-12": "Anne Frank began her diary today in 1942 — 'diary' comes from Latin *diarium*, a daily allowance, then a daily record.",
    "06-13": "'Verdict' comes from Latin *veredictum*, a true saying — from *vere* (truly) + *dictum* (said).",
    "06-14": "'Flag' is of uncertain origin, possibly from a Low German word meaning to flap — Flag Day is observed today in the US.",
    "06-15": "Magna Carta was sealed today in 1215 — Latin for 'Great Charter,' the foundational document of English common law.",
    "06-16": "Bloomsday — the date James Joyce set *Ulysses*, from 1904 — 'Ulysses' is the Latin form of the Greek name 'Odysseus.'",
    "06-17": "'Watergate' became a global suffix for political scandals after the burglary today in 1972.",
    "06-18": "'Guillotine' was named after Dr. Joseph-Ignace Guillotin, who advocated for it as a more humane execution method.",
    "06-19": "'Juneteenth' is a portmanteau of 'June' + 'nineteenth' — marking the end of slavery in the US on June 19, 1865.",
    "06-20": "'Solstice' from Latin *sol* (sun) + *sistere* (to stand still) — the moment the sun appears to pause at its highest point.",
    "06-21": "'Midsummer' magic filled Shakespeare's *A Midsummer Night's Dream*, set on this mystical, liminal night.",
    "06-22": "'Cryptography' from Greek *kryptos* (hidden) + *graphein* (to write) — Alan Turing's WWII codebreaking saved millions of lives.",
    "06-23": "The word 'computer' originally meant a person who computes — Turing proposed machines could do it instead, today in 1948.",
    "06-24": "'Bonfire' comes from 'bone fire' — medieval bonfires often burned animal bones, not wood, especially at midsummer.",
    "06-25": "'Anthem' comes from Greek *antiphōnon*, a hymn sung in alternating parts — call and response.",
    "06-26": "The United Nations Charter was signed today in 1945 — 'united' from Latin *unire*, to join into one.",
    "06-27": "Helen Keller was born today in 1880 — she became the first deaf-blind person to earn a bachelor of arts degree.",
    "06-28": "Louis Braille was born today in 1809 — his tactile writing system let millions of blind people access the written word.",
    "06-29": "'Peter' comes from Greek *petros*, rock — the feast of Saints Peter and Paul is today in Catholic tradition.",
    "06-30": "Einstein published his special theory of relativity today in 1905 — 'relativity' from Latin *relativus*, brought back into relation.",

    # ── July ─────────────────────────────────────────────────────────────────
    "07-01": "'Canada' (Confederation, 1867) may come from *kanata*, a Huron-Iroquois word for 'village' or 'settlement.'",
    "07-02": "'Kafkaesque' — describing nightmarish bureaucracy — comes from Franz Kafka, born today in 1883.",
    "07-03": "'Independence' from Latin *in-* (not) + *dependere* (to hang from) — the Declaration was adopted on this day in 1776.",
    "07-04": "The Declaration of Independence used 'self-evident truths' — a phrase Jefferson coined, replacing 'sacred and undeniable.'",
    "07-05": "P.T. Barnum was born today in 1810 — 'circus' comes from Latin for a circular racecourse.",
    "07-06": "'Hologram' from Greek *holos* (whole) + *gramma* (letter/drawing) — a picture that holds the whole image.",
    "07-07": "'Jingle' echoes the sound of small bells — from Middle English, imitating the ringing clatter.",
    "07-08": "'Alien' comes from Latin *alienus*, belonging to another — the Roswell UFO incident was reported today in 1947.",
    "07-09": "'Bikini' was named after Bikini Atoll, a nuclear test site — its 1946 designer expected it to be 'explosive.'",
    "07-10": "Nikola Tesla was born today in 1856 — 'electricity' from Greek *elektron*, amber, which the ancients noticed attracted things when rubbed.",
    "07-11": "'Oasis' comes from the Egyptian *wḥꜣt*, a fertile area — the word was absorbed into Greek, Latin, and then English.",
    "07-12": "Malala Yousafzai was born today in 1997 — her name comes from Pashto, meaning grief-stricken.",
    "07-13": "'Charity' comes from Old French *charité*, from Latin *caritas* (love or esteem) — Live Aid raised millions today in 1985.",
    "07-14": "Bastille Day — 'Bastille' from Old French *bastide*, a fortified building, stormed on July 14, 1789.",
    "07-15": "'Limerick' as a poem form was popularised by Edward Lear, who may have named it after the Irish city.",
    "07-16": "Apollo 11 launched today in 1969 — 'astronaut' literally means 'star-sailor' in Greek.",
    "07-17": "'Emoji' comes from Japanese *e* (picture) + *moji* (character) — the first emoji set was created by Shigetaka Kurita in 1999.",
    "07-18": "Nelson Mandela was born today in 1918 — the 'Mandela effect' describes false collective memories, named after him.",
    "07-19": "'Suffrage' comes from Latin *suffragium*, a vote or prayer — the Seneca Falls Convention launched women's suffrage today in 1848.",
    "07-20": "Neil Armstrong's moon landing words today in 1969 — 'one small step for man' lost the article 'a' in radio transmission.",
    "07-21": "'Cipher' comes from Arabic *ṣifr*, meaning zero — the same root as 'zero' itself, both from the concept of nothingness.",
    "07-22": "'Mantra' from Sanskrit — *man* (to think) + *tra* (tool) — a thinking tool, a phrase that focuses the mind.",
    "07-23": "Amelia Earhart was born today in 1897 — 'aviator' from Latin *avis* (bird), the one who flew like birds.",
    "07-24": "'Berserk' comes from Old Norse *berserkr*, a Viking warrior who fought in a frenzy — literally 'bear shirt' or 'bare shirt.'",
    "07-25": "The Americans with Disabilities Act was signed today in 1990 — 'disability' from Latin *dis-* (not) + *habilis* (fit).",
    "07-26": "'Armistice' comes from Latin *armistitium*, a stoppage of arms — the Korean War armistice was signed today in 1953.",
    "07-27": "'Mole' in chemistry comes from Latin *molecula* (little mass) — a unit that makes the invisible countable.",
    "07-28": "NASA was established today in 1958 — 'aeronautics' from Greek *aer* (air) + *nautes* (sailor).",
    "07-29": "Henry Ford was born today in 1863 — 'automobile' from Greek *auto* (self) + Latin *mobilis* (movable).",
    "07-30": "Harry Potter's fictional birthday is today — J.K. Rowling invented words like 'Muggle,' 'Quidditch,' and 'Horcrux.'",
    "07-31": "J.K. Rowling was born today in 1965 — she gave 'Muggle' to the Oxford English Dictionary, a word for a non-magical person.",

    # ── August ───────────────────────────────────────────────────────────────
    "08-01": "'August' is named after Emperor Augustus — the Latin word *augustus* means majestic or venerable.",
    "08-02": "'Cowboy' first appeared in print around 1849 — 'aces and eights,' Wild Bill Hickok's hand, became 'the Dead Man's Hand.'",
    "08-03": "'Virus' comes from Latin *virus*, poison or slime — Columbus sailed from Spain today in 1492 in search of a new route.",
    "08-04": "'Barack' is a Swahili and Hebrew name meaning 'blessed' — Barack Obama was born today in 1961.",
    "08-05": "Neil Armstrong was born today in 1930 — 'Houston, we have a problem' is one of the most misquoted sentences in history.",
    "08-06": "'Nuclear' from Latin *nucleus*, a kernel — the atomic bomb dropped on Hiroshima today in 1945.",
    "08-07": "'Work' comes from Old English *weorc* — 'labor' from Latin *labor*, toil; both describe the same fundamental human activity.",
    "08-08": "The mathematical symbol for infinity (∞) was introduced by John Wallis in 1655 — possibly inspired by the Roman numeral M.",
    "08-09": "'Nagasaki' means 'long cape' in Japanese — the city sits at the end of a long peninsula.",
    "08-10": "'Herculean' describes tasks of extreme difficulty — from Hercules, whose twelve labours define the word.",
    "08-11": "'Aloha' in Hawaiian means both hello and goodbye, and also love, peace, and compassion — perhaps the world's most versatile word.",
    "08-12": "'Adolescent' from Latin *adolescere*, to grow up — International Youth Day marks the stage between child and adult.",
    "08-13": "Alfred Hitchcock was born today in 1899 — the 'MacGuffin,' a plot object that motivates characters, is his contribution to storytelling vocabulary.",
    "08-14": "V-J Day, 1945 — 'victory' from Latin *victoria*; Japan's surrender ended the bloodiest conflict in human history.",
    "08-15": "Napoleon was born today in 1769 — his campaigns seeded military vocabulary: 'bivouac,' 'forage,' and 'billet' in English.",
    "08-16": "'Madonna' comes from Italian *ma donna*, 'my lady' — originally a term of reverence for the Virgin Mary.",
    "08-17": "'Malware' is a 1990s portmanteau of 'malicious' + 'software' — one of the few tech words invented entirely for the digital age.",
    "08-18": "'Photograph' from Greek *phos* (light) + *graphein* (to write) — Daguerre presented his process to the world today in 1839.",
    "08-19": "'Mosquito' from Spanish *mosca* (fly) + diminutive *-ito* — literally 'little fly,' an understatement for such a deadly creature.",
    "08-20": "'Rebel' from Latin *rebelare*, to make war again — Nat Turner's rebellion began today in 1831.",
    "08-21": "'Debonair' from Old French *de bon aire*, of good manner or lineage — a word that radiates effortless sophistication.",
    "08-22": "'Satellite' from Latin *satelles*, an attendant or companion — the first US communications satellite launched today in 1962.",
    "08-23": "Pompeii was buried by Vesuvius today in 79 AD — 'volcano' from *Vulcanus*, the Roman god of fire.",
    "08-24": "Carl Sagan's famous line 'We are made of star-stuff' gave everyday poetry to the science of nuclear fusion.",
    "08-25": "The 19th Amendment was certified today in 1920, giving US women the right to vote — 'suffrage' from Latin *suffragium*.",
    "08-26": "'Petroleum' from Latin *petra* (rock) + *oleum* (oil) — the first successful US oil well was drilled today in 1859.",
    "08-27": "On this day in 1963, Martin Luther King Jr. delivered 'I Have a Dream' — 'dream' from Old English *drēam*, originally meaning joy.",
    "08-28": "'Hurricane' from Spanish *huracán*, borrowed from the Taíno *hurakán*, a Caribbean wind god.",
    "08-29": "Mary Shelley was born today in 1797 — 'Frankenstein' has become an eponym for dangerous science that escapes its creator.",
    "08-30": "'Ad nauseam' means literally 'to the point of nausea' in Latin — a phrase for anything repeated until we're sick of it.",
    "08-31": "The word 'September' comes from Latin *septem* (seven) — a reminder that August was inserted by emperors, shoving the months back.",

    # ── September ────────────────────────────────────────────────────────────
    "09-01": "'September' from Latin *septem* (seven) — it was the 7th month before Julius and Augustus Caesar added their namesake months.",
    "09-02": "The Great Fire of London began today in 1666 — 'inferno' from Latin *infernus*, of the underworld.",
    "09-03": "The Treaty of Paris ending the American Revolution was signed today in 1783 — 'treaty' from Latin *tractatus*, a drawing out.",
    "09-04": "'Los Angeles' means 'The Angels' in Spanish — the city was founded today in 1781.",
    "09-05": "'Labyrinth' comes from Greek *labyrinthos*, possibly from *labrys*, the double-headed axe of Minoan Crete.",
    "09-06": "'Pilgrim' from Latin *peregrinus*, a traveler, stranger, or foreigner — the Mayflower set sail today in 1620.",
    "09-07": "Elizabeth I was born today in 1533 — one of England's most eloquent monarchs, whose speeches shaped Tudor prose.",
    "09-08": "International Literacy Day — 'literate' from Latin *litteratus*, one acquainted with letters.",
    "09-09": "'Chronology' from Greek *khronos* (time) + *logos* (study) — the science of putting events in the right order.",
    "09-10": "'Stitch' from Old English *stice*, a piercing — Elias Howe patented the sewing machine today in 1846.",
    "09-11": "'Resilience' from Latin *resilire*, to spring back — a word of profound weight in relation to this date.",
    "09-12": "JFK said 'We choose to go to the moon' today in 1962 — 'astronaut' from Greek *astron* (star) + *nautes* (sailor).",
    "09-13": "Roald Dahl was born today in 1916 — he coined 'splendiferous,' 'whizzpopping,' and 'scrumdiddlyumptious.'",
    "09-14": "Francis Scott Key wrote the poem that became 'The Star-Spangled Banner' today in 1814, published in a newspaper the same day.",
    "09-15": "Agatha Christie was born today in 1890 — she introduced 'whodunit' to describe the mystery fiction genre she perfected.",
    "09-16": "Mexico declared independence today in 1810 — 'revolution' from Latin *revolutio*, a turning around.",
    "09-17": "The US Constitution was signed today in 1787 — its 'Preamble' comes from Latin *praeambulare*, to walk before.",
    "09-18": "'Pirate' from Greek *peiratēs*, one who attacks at sea — International Talk Like a Pirate Day is today.",
    "09-19": "'Equinox' — the autumnal one falls around September 22-23 — from Latin *aequus* (equal) + *nox* (night).",
    "09-20": "The word 'autumn' comes from Latin *autumnus*, possibly from Etruscan *autume* — the season of harvest and endings.",
    "09-21": "J.R.R. Tolkien published *The Hobbit* today in 1937, introducing one of literature's most beloved invented words.",
    "09-22": "Both Bilbo Baggins and Frodo share September 22 as their birthday in Tolkien's lore — fiction's most famous coincidence.",
    "09-23": "'Punctuation' from Latin *punctuare*, to mark with points — the comma was invented by Aldus Manutius around 1490.",
    "09-24": "'Cathedral' from Latin *cathedra* (chair) — a bishop's seat; 'ex cathedra' means speaking with full authority.",
    "09-25": "'Gibberish' may derive from the alchemist Jabir ibn Hayyan, whose obscure Latin writings were hard to decipher.",
    "09-26": "Google was incorporated today in 1998 — 'googol' (10¹⁰⁰) was coined by a 9-year-old, and the founders misspelled it.",
    "09-27": "Confucius was born today in 551 BCE — he said: 'Without knowing the force of words, it is impossible to know anything else.'",
    "09-28": "'Michaelmas' (September 29) — 'Michael' from Hebrew meaning 'who is like God?' — a question, not a statement.",
    "09-29": "Rumi was born today in 1207 — his Persian poetry is among the most widely read in the world, even centuries after his death.",
    "09-30": "'October' comes from Latin *octo* (eight) — once the 8th month before January and February were added to the calendar.",

    # ── October ──────────────────────────────────────────────────────────────
    "10-01": "'October' from Latin *octo* (eight) — the months of the year carry the ghosts of a calendar that no longer exists.",
    "10-02": "Mahatma Gandhi was born today in 1869 — 'Mahatma' is Sanskrit for 'great soul,' *maha* (great) + *atma* (soul).",
    "10-03": "'Glamour' and 'grammar' are the same word — Scottish folklore linked arcane book-learning to magic, and the spelling drifted.",
    "10-04": "Sputnik launched today in 1957 — 'Sputnik' means 'fellow traveler' in Russian, from *put'* (path) + *nik* (one who does).",
    "10-05": "'Zen' from Chinese *chán*, from Sanskrit *dhyāna*, meditation — a whole philosophy compressed into a single syllable.",
    "10-06": "The first major talking picture, *The Jazz Singer*, premiered today in 1927 — 'video' comes from Latin *videre*, to see.",
    "10-07": "'Archipelago' from Italian, the Aegean Sea — from Greek *archi* (chief) + *pelagos* (sea).",
    "10-08": "The Great Chicago Fire began today in 1871 — 'inferno' comes from Dante's *Inferno*, the nine circles of hell.",
    "10-09": "Korean Alphabet Day celebrates Hangul (proclaimed 1443) — one of the few writing systems with a known single inventor.",
    "10-10": "'Decimal' from Latin *decimus*, tenth — on 10/10, it is worth remembering humanity built all maths on ten fingers.",
    "10-11": "Eleanor Roosevelt was born today in 1884 — 'suffragette' added the French diminutive '-ette' to the powerful word 'suffrage.'",
    "10-12": "'Discover' from Latin *discooperire*, to uncover — Columbus's arrival in 1492 is a reminder that 'discovery' has a perspective.",
    "10-13": "'Navigate' from Latin *navis* (ship) + *agere* (to drive) — the Continental Navy was established today in 1775.",
    "10-14": "'Palindrome' (reads the same backward) — from Greek *palin* (again) + *dromos* (running).",
    "10-15": "'Mushroom' from Old French *mousseron*, possibly from *mousse* (moss) — fungi that grew in moss-covered places.",
    "10-16": "World Food Day — 'hunger' from Old English *hungor*; the UN Food and Agriculture Organization was founded today in 1945.",
    "10-17": "'Jazz' appeared in print as early as 1912 — playwright Arthur Miller was born today in 1915.",
    "10-18": "Alaska was formally transferred to the US today in 1867 — 'Alaska' comes from the Aleut *alaxsxaq*, 'the great land.'",
    "10-19": "'Trafalgar' is Arabic for 'Cape of the Cave' — *taraf al-ghar* — where Nelson defeated Napoleon's fleet in 1805.",
    "10-20": "'Censorship' from Latin *censor*, a Roman official who assessed both taxes and public morality.",
    "10-21": "Alfred Nobel was born today in 1833 — he invented dynamite; 'dynamite' from Greek *dynamis* (power).",
    "10-22": "'Palindrome' dates recognised as palindromic include 10/22/2001 — a quirk of the calendar that language notices.",
    "10-23": "Archbishop Ussher calculated the world was created today in 4004 BCE — an example of false precision that language can conceal.",
    "10-24": "United Nations Day — 'united' from Latin *unitus*, joined into one; the UN was founded on today's date in 1945.",
    "10-25": "Shakespeare's Henry V immortalised the Battle of Agincourt (1415): 'We few, we happy few, we band of brothers.'",
    "10-26": "'Frankenstein' was conceived by Mary Shelley in 1816 — the name has become an eponym for creation that destroys its maker.",
    "10-27": "Theodore Roosevelt was born today in 1858 — he coined 'muckraker' for investigative journalists exposing corruption.",
    "10-28": "'Liberty' from Latin *libertas* — the Statue of Liberty was dedicated today in 1886.",
    "10-29": "Black Tuesday, 1929 — 'crash' was first used for financial collapse in the early 20th century.",
    "10-30": "'Martian' from Mars, the war god — Orson Welles's *War of the Worlds* broadcast panicked radio listeners today in 1938.",
    "10-31": "'Halloween' from 'All Hallows' Eve' — 'hallow' from Old English *hālgian*, to make holy, the night before All Saints' Day.",

    # ── November ─────────────────────────────────────────────────────────────
    "11-01": "All Saints' Day — 'saint' from Latin *sanctus*, holy; 'Día de los Muertos' celebrates those who have passed.",
    "11-02": "'Muertos' (Day of the Dead) from Latin *mortuus*, dead — a word shared by 'mortgage,' literally a 'dead pledge.'",
    "11-03": "'Sandwich' is named after the 4th Earl of Sandwich, who ate meat between bread slices to avoid leaving his gambling table.",
    "11-04": "'Ballot' from Italian *ballotta*, a small ball — ancient Greeks voted by dropping coloured pebbles into jars.",
    "11-05": "Guy Fawkes Day — 'guy' entered English as a word for a grotesque effigy of Fawkes, and eventually for any person.",
    "11-06": "'Saxophone' — one of the few musical instruments named after its inventor, Adolphe Sax, born 1814.",
    "11-07": "Marie Curie was born today in 1867 — she coined the term 'radioactivity' and was the first to use the word in French.",
    "11-08": "Wilhelm Röntgen discovered X-rays today in 1895 — he called them 'X-rays' because X denotes an unknown quantity.",
    "11-09": "The Berlin Wall fell today in 1989 — 'wall' from Latin *vallum*, a palisade of stakes used in Roman fortifications.",
    "11-10": "'Marine' from Latin *mare*, sea — the United States Marine Corps was established today in 1775.",
    "11-11": "Armistice Day — WWI ended at the 11th hour of the 11th day of the 11th month; 'armistice' from Latin *armistitium*.",
    "11-12": "'Voyage' from Old French *voyage*, from Latin *viaticum*, provisions for a journey — travel is about the word as much as the road.",
    "11-13": "International Kindness Day — 'kindness' from Old English *gecyndnes*, natural quality — to be kind is to act in your true nature.",
    "11-14": "'India' from the Indus River, from Sanskrit *Sindhu* (river) — Nehru was born today in 1889.",
    "11-15": "'Brazil' comes from *pau-brasil*, brazilwood — a tree whose red dye was so valuable it gave a country its name.",
    "11-16": "'Television' from Greek *tele* (far) + Latin *visio* (sight) — seeing from a distance.",
    "11-17": "The Suez Canal opened today in 1869 — 'canal' from Latin *canalis*, a channel, the same root as 'channel.'",
    "11-18": "Mickey Mouse debuted today in 1928 — 'mickey' later entered British slang, and 'Mickey Mouse' became a phrase for worthless.",
    "11-19": "Lincoln delivered the Gettysburg Address today in 1863 — 272 words that redefined the purpose of the American republic.",
    "11-20": "'Gender' comes from Latin *genus*, type or kind — Transgender Remembrance Day falls today.",
    "11-21": "Voltaire was born today in 1694 — he said: 'Those who can make you believe absurdities can make you commit atrocities.'",
    "11-22": "'Gobbledygook' was coined by Texas Congressman Maury Maverick in 1944 for incomprehensible bureaucratic language.",
    "11-23": "'Turkey' the bird got its English name by confusion — early traders thought it came from Turkey, but it is native to the Americas.",
    "11-24": "Darwin published *On the Origin of Species* today in 1859 — 'evolution' from Latin *evolutio*, an unrolling.",
    "11-25": "'Charisma' from Greek *kharisma*, a gift of grace — something given, not earned, that moves people.",
    "11-26": "'Casablanca' is Spanish for 'White House' — *casa* (house) + *blanca* (white) — a name hiding in plain sight.",
    "11-27": "Anders Celsius was born today in 1701 — the thermometer gave us a vocabulary for heat that the body could not provide alone.",
    "11-28": "'Black Friday' was originally a term for financial panics, not shopping — the 1869 gold market crash coined it.",
    "11-29": "Louisa May Alcott was born today in 1832 — *Little Women* (1868) shaped the language of American girls' coming-of-age stories.",
    "11-30": "Mark Twain was born today in 1835 — he said: 'The difference between the right word and the almost-right word is lightning versus a lightning bug.'",

    # ── December ─────────────────────────────────────────────────────────────
    "12-01": "'December' from Latin *decem* (ten) — once the 10th month, now the 12th, carrying its old name like a forgotten address.",
    "12-02": "'Abolition' from Latin *abolitio*, annulment — to undo what had been written into law.",
    "12-03": "'Catastrophe' from Greek *katastrophē*, an overturning — the Bhopal disaster today in 1984 was a catastrophe in every sense.",
    "12-04": "Rainer Maria Rilke was born today in 1875 — his *Letters to a Young Poet* remains the definitive guide to a writer's inner life.",
    "12-05": "Prohibition ended in the US today in 1933 — 'prohibition' from Latin *prohibere*, to hold back.",
    "12-06": "Finland gained independence today in 1917 — 'Suomi' (Finnish for Finland) may derive from a Proto-Baltic word meaning 'land.'",
    "12-07": "FDR called this date in 1941 'a date which will live in infamy' — 'infamy' from Latin *infamia*, bad reputation.",
    "12-08": "John Lennon was shot today in 1980 — 'Beatle' was a play on 'beat' music + 'beetle,' like Buddy Holly's band The Crickets.",
    "12-09": "'Eureka' — Greek for 'I have found it!' — is what Archimedes reportedly shouted when he discovered water displacement.",
    "12-10": "Nobel Prize Day — Alfred Nobel died today in 1896; prizes are awarded annually on this date, funded by his dynamite fortune.",
    "12-11": "UNICEF was established today in 1946 — 'emergency' from Latin *emergere*, to rise out of, to come to the surface.",
    "12-12": "'Guadalupe' from Arabic *wādī* (river valley) + Latin *lupus* (wolf) — the wolf river, now a day of celebration.",
    "12-13": "'Lucia' (St. Lucia Day) from Latin *lux*, light — the festival of light in the darkest weeks of the year.",
    "12-14": "Roald Amundsen reached the South Pole today in 1911 — 'pole' from Greek *polos*, axis, the point on which everything turns.",
    "12-15": "The Bill of Rights was ratified today in 1791 — 'right' from Old English *riht*, that which is proper or just.",
    "12-16": "The Boston Tea Party happened today in 1773 — 'boycott' didn't exist yet; 'protest' and 'liberty' filled the pamphlets.",
    "12-17": "The Wright Brothers made the first powered flight today in 1903 — 'Wright' from Old English *wyrhta*, a worker or craftsman.",
    "12-18": "'Saturnalia' — the Roman winter festival (Dec 17–23) — was so raucous that 'saturnalia' came to mean any wild revelry.",
    "12-19": "'Noël' (French for Christmas) comes from Latin *natalis*, of birth — the same root as 'natal' and 'nativity.'",
    "12-20": "'Purchase' from Old French *purchacier*, to acquire by effort — the Louisiana Purchase today in 1803 doubled the US.",
    "12-21": "'Solstice' from Latin *sol* (sun) + *sistere* (to stand still) — the shortest day, when the sun seems to pause in the sky.",
    "12-22": "'Yule' comes from Old Norse — a midwinter festival that gave English 'Yuletide' and the tradition of the Yule log.",
    "12-23": "'Advent' from Latin *adventus*, an arrival or coming — the season of anticipation before a word-changing event.",
    "12-24": "'Midnight' splits Christmas Eve from Christmas Day — 'advent' literally means arrival, and midnight is when it comes.",
    "12-25": "'Christmas' from Old English *Crīstesmæsse*, Christ's mass — and 'Noel' has graced carols since the 14th century.",
    "12-26": "'Boxing Day' — 'box' here refers to a Christmas box, the tradition of giving gifts to servants and tradespeople.",
    "12-27": "Johannes Kepler was born today in 1571 — 'planet' from Greek *planetes*, wanderer — they 'wandered' against the fixed stars.",
    "12-28": "'Innocent' from Latin *innocens*, not harming — Holy Innocents' Day, historically considered the unluckiest of the year.",
    "12-29": "Texas joined the Union today in 1845 — 'Texas' from the Caddo *taysha*, meaning friend or ally.",
    "12-30": "Rudyard Kipling was born today in 1865 — 'jungle' (from *The Jungle Book*) came from Hindi *jangal*, a wasteland.",
    "12-31": "'Auld lang syne' is Scots for 'old long since' — we close the year with a phrase mourning and celebrating time itself.",
}


def get_word_fact(month: int, day: int) -> str:
    """Return the word-history fact for the given month/day, with a safe fallback."""
    key = f"{month:02d}-{day:02d}"
    return WORD_HISTORY.get(key, "Every word you know was once a new invention — and today one more waits to be solved.")
